export const LANDING_PAGE_QUERY = `
    *[_type == 'landingPage'][0]{
        carousel[]->{
            _id,
            title,
            caption,
            year,
            dimensions,
            medium,
            mainImage{
                alt,
                caption,
                hotspot,
                crop,
                asset->{
                    _id,
                    url,
                    originalFilename,
                    title,
                    path,
                    size,
                    metadata{
                        blurHash,
                        lqip,
                        dimensions{
                            width,
                            height,
                            aspectRatio
                        }
                    }
                }
            }
        }
    }
`;